[server]
host = "0.0.0.0"
port = 8080
root = "html"
default_error_page = "httpError/template/template.html"
error_page_403 = "example/error/403.html"
error_page_404 = "example/error/404.html"
error_page_502 = "example/error/502.html"

[server.route]
root = "html"
methods = ["GET"]
default_file = "index.html"
autoindex = false
